### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [raku-community-modules/Shell-Command#27]
1.
Can you please set a specific "version" for your RAKU module in your META6.json file?
You have a '*" now, which is known to make trouble and may not be supported within the RAKU tool chain (soon), say ZEF, FEZ, MI6...

2.
Can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?

I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by lizmat** [comment]
Release 1.0 was just tagged
